language: csharp
solution: Gerbil.sln
mono:
  - latest
env:
  - CFG=Debug
  - CFG=Release
install:
  - nuget restore Gerbil.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=$CFG /target:Gerbil Gerbil.sln
#  - ./scripts/build.sh
test:
  - mono ./testrunner/NUnit.Runners.*/tools/nunit-console.exe ./GerbilTest/bin/$CFG/GerbilTest.dll
#  - ./scripts/test.sh
